# Default from https://github.com/sxyazi/yazi/tree/latest/yazi-config/preset
[opener]
edit = [
  { run = '${EDITOR:=vi} %s', block = true, desc = "$EDITOR file", for = "unix" },
  # Use Helix instead of code
  { run = '%EDITOR% %s', block = true, desc = "$EDITOR file", for = "windows" },
]

[open]
# Add rules to the default to avoid overwriting defaults
append_rules = [
  { mime = "text/*", use = "edit" },
  # Various text files use this MIME type
  # Check MIMI type in Yazi using Tab
  { mime = "application/octet-stream", use = "edit" },
  # { mime = "application/json", use = "edit" },
  { url = "*.json", use = "edit" },
]

[mgr]
# Show hidden files by default
show_hidden = true

[preview]
# Word wrap code preview
# wrap = "yes"

# MIME type retrieval plugin
# https://github.com/yazi-rs/plugins/tree/main/mime-ext.yazi
[[plugin.prepend_fetchers]]
url = "local://*"
run = "mime-ext.local"
prio = "high"
group = "mime"

[[plugin.prepend_fetchers]]
url = "remote://*"
run = "mime-ext.remote"
prio = "high"
group = "mime"

# Disable Image, Video Previews
# https://yazi-rs.github.io/docs/configuration/yazi#plugin.previewers
[plugin]
prepend_previewers = [
  { mime = "image/*", run = "noop" },
  { mime = "video/*", run = "noop" },
  { mime = "application/octet-stream", run = "code" },
  { mime = "application/xml", run = "code" },
]
