# Windows configuration location: %APPDATA%\alacritty\
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal]
# Windows: change from default powershell
# shell = "pwsh"

[colors.primary]
background = "#000000"
