theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"
# Hightlight background of line that cursor is on
cursorline = true

[editor.lsp]
# Inline hints
display-inlay-hints = true

[editor.inline-diagnostics]
# https://helix-editor.com/news/release-25-01-highlights/ diagnostics section
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
# Minimum severity to show a diagnostic on other lines:
# other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Soft-wrap breaks up lines to fit in view without inserting actual 
# line break characters into the text (so called "hard-wrapping")
[editor.soft-wrap]
enable = true
# Remove the wrap indicator symbol
wrap-indicator = ""

[editor.file-picker]
hidden = false

[keys.insert]
# Maps `jk` to exit insert mode
# per https://docs.helix-editor.com/remapping.html
j = { k = "normal_mode" } 
