[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = [] }

[language-server.rust-analyzer.config]
cargo = { features = "all" }
check.command = "clippy"

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true
formatter = { command = "black", args = ["-"] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "yaml"
auto-format = true
file-types = [ "yaml", "yml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }
