[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = [] }

[language-server.rust-analyzer.config]
cargo = { features = "all" }
check.command = "clippy"

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true
formatter = { command = "black", args = ["-"] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
# if you choose `ruff` itself
[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "yaml"
auto-format = true
file-types = ["yaml", "yml"]
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'shfmt', args = ["-i", "2"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
formatter = { command = 'prettier', args = ["--parser", "scss"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

# Suggestions from
# https://helix-editor-tutorials.com/tutorials/writing-documentation-and-prose-in-markdown-using-helix/
[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls-plus"]
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",       # <always|never|preserve>
] }
# For use with :reflow to hard wrap
text-width = 80
auto-format = true

# Inspired by https://github.com/doomemacs/doomemacs/pull/6683
[[language]]
name = "org"
language-servers = ["ltex-ls-plus"]
